# Generated by Django 5.0.6 on 2024-06-11 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_description', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=50)),
                ('urgency_level', models.CharField(max_length=20)),
                ('submitted_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'issue',
            },
        ),
    ]
