# Generated by Django 5.0.6 on 2024-06-11 17:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_sys', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('reply_date', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk_sys.issue')),
            ],
            options={
                'db_table': 'issueresponse',
            },
        ),
    ]
