# Generated by Django 5.0.6 on 2024-06-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_sys', '0003_issueresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issued_by',
            new_name='user',
        ),
    ]
