# Generated by Django 5.0.6 on 2024-07-01 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_sys', '0005_issue_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issueresponse',
            old_name='description',
            new_name='response',
        ),
    ]
