# Generated by Django 5.0.6 on 2024-07-01 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_sys', '0006_rename_description_issueresponse_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_text', models.TextField()),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk_sys.issueresponse')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
